const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("catcut", {
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (input) => ipcRenderer.invoke("settings:save", input),
  listFontProfiles: () => ipcRenderer.invoke("font-profiles:list"),
  saveFontProfile: (input) => ipcRenderer.invoke("font-profiles:save", input),
  deleteFontProfile: (profileId) => ipcRenderer.invoke("font-profiles:delete", profileId),
  getTelopPresets: () => ipcRenderer.invoke("telop-presets:list"),
  getTelopTypeMapping: () => ipcRenderer.invoke("telop-type-mapping:get"),
  saveTelopTypeMapping: (input) => ipcRenderer.invoke("telop-type-mapping:save", input),
  getUserRules: () => ipcRenderer.invoke("user-rules:get"),
  saveUserRules: (input) => ipcRenderer.invoke("user-rules:save", input),
  learnDictionaryRule: (input) => ipcRenderer.invoke("user-rules:learnDictionary", input),
  getUserDictionary: () => ipcRenderer.invoke("user-dictionary:get"),
  saveUserDictionaryEntry: (input) => ipcRenderer.invoke("user-dictionary:save", input),
  deleteUserDictionaryEntry: (from) => ipcRenderer.invoke("user-dictionary:delete", from),
  recordLearningDecision: (input) => ipcRenderer.invoke("user-rules:recordDecision", input),
  chooseVideo: () => ipcRenderer.invoke("dialog:chooseVideo"),
  chooseGroundTruthText: () => ipcRenderer.invoke("ground-truth:choose"),
  analyzeGroundTruthRules: (input) => ipcRenderer.invoke("ground-truth:analyze", input),
  applyGroundTruthRuleProposal: (input) => ipcRenderer.invoke("ground-truth:apply-rule-proposal", input),
  applyGroundTruthText: (input) => ipcRenderer.invoke("ground-truth:apply", input),
  chooseOutputDirectory: () => ipcRenderer.invoke("dialog:chooseOutputDirectory"),
  saveOutputFile: (input) => ipcRenderer.invoke("dialog:saveOutputFile", input),
  startJob: (options) => ipcRenderer.invoke("job:start", options),
  startExport: (options) => ipcRenderer.invoke("export:start", options),
  cancelJob: () => ipcRenderer.invoke("job:cancel"),
  loadTelop: (runDir) => ipcRenderer.invoke("telop:load", runDir),
  loadTranscriptEditor: (runDir) => ipcRenderer.invoke("transcript:load", runDir),
  applyTranscriptEdits: (input) => ipcRenderer.invoke("transcript:apply", input),
  runTranscriptCommand: (input) => ipcRenderer.invoke("transcript:run-command", input),
  generateWaveform: (input) => ipcRenderer.invoke("transcript:waveform", input),
  saveTelop: (input) => ipcRenderer.invoke("telop:save", input),
  applyFontDirectives: (input) => ipcRenderer.invoke("font:apply", input),
  applyTelopStyle: (input) => ipcRenderer.invoke("telop-style:apply", input),
  getOllamaStatus: () => ipcRenderer.invoke("ollama:status"),
  pullOllamaModel: (input) => ipcRenderer.invoke("ollama:pull", input),
  reviewTelopWithOllama: (input) => ipcRenderer.invoke("ollama:review-telop", input),
  openOllamaInstallGuide: () => ipcRenderer.invoke("ollama:openInstallGuide"),
  revealPath: (targetPath) => ipcRenderer.invoke("path:reveal", targetPath),
  openPath: (targetPath) => ipcRenderer.invoke("path:open", targetPath),
  getApiKeysStatus: () => ipcRenderer.invoke("api-keys:status"),
  setApiKey: (input) => ipcRenderer.invoke("api-keys:set", input),
  deleteApiKey: (input) => ipcRenderer.invoke("api-keys:delete", input),
  testApiKey: (input) => ipcRenderer.invoke("api-keys:test", input),
  openExternalUrl: (url) => ipcRenderer.invoke("shell:openExternal", url),
  onJobEvent: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on("job:event", handler);
    return () => ipcRenderer.removeListener("job:event", handler);
  },
});
